### ISSUE TITLE
Miranda reader does not work with serial data in newer format

### ISSUE THREAD

**Issue by akshaysubr** [FPAL-Stanford-University/FloATPy#35]
Miranda reader with the newer format and a single processor run returns a zero array for all fields including coordinates. For a `128x128x1` 2D problem, looks like `self.px, seld.py, self.pz == 0, 0, 1` with `self.nx, seld.ny, self.nz == 128, 128, 1` and  `self.ax, seld.ay, self.az == 129, 129, 1`. Maybe an issue with handling of ghost point indexing in the reader?

**Comment by akshaysubr** [comment]
Changing https://github.com/FPAL-Stanford-University/FloATPy/blob/9628b87c484273ca2515a9b114fff06e51211998/floatpy/readers/miranda_reader.py#L99-L101 to 
```
# Fix the local indices                      
if self.nx > 1:                              
    self.ax -=  1 #numpy.minimum(self.px-1,1)
if self.ny > 1:                              
    self.ay -=  1 #numpy.minimum(self.py-1,1)
if self.nz > 1:                              
    self.az -=  1 #numpy.minimum(self.pz-1,1)
```
seems to fix the issue. @flow-phys could you check if this fix is correct?

**Comment by flow-phys** [comment]
@akshaysubr , this looks about right, though I'd need to check that this doesn't break the parallel version.

**Comment by akshaysubr** [comment]
Fixed this issue in the latest pull request. Checked that the fix works with the parallel reader as well. Closing this issue.
